services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: notif_user
      POSTGRES_PASSWORD: notif_pass
      POSTGRES_DB: notif_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file: .env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: ["sh", "-c", "node worker.js"] 

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  
      - "1025:1025"       

volumes:
  pgdata:
  redisdata:
